#include "html_reporter.h"

#include <filesystem>
#include <fstream>
#include <sstream>

namespace
{
    std::string EscapeHtml(
        const std::string& value)
    {
        std::string escaped;
        escaped.reserve(value.size());

        for (const char ch : value)
        {
            switch (ch)
            {
            case '&': escaped += "&amp;"; break;
            case '<': escaped += "&lt;"; break;
            case '>': escaped += "&gt;"; break;
            case '"': escaped += "&quot;"; break;
            case '\'': escaped += "&#39;"; break;
            default: escaped += ch; break;
            }
        }

        return escaped;
    }

    std::string EscapeJsonForHtmlScript(
        const std::string& json)
    {
        std::string escaped;
        escaped.reserve(json.size());

        for (const char ch : json)
        {
            switch (ch)
            {
            case '<': escaped += "\\u003c"; break;
            case '>': escaped += "\\u003e"; break;
            case '&': escaped += "\\u0026"; break;
            default: escaped += ch; break;
            }
        }

        return escaped;
    }

    const char* HtmlTemplate()
    {
        return R"RABBITX_HTML(<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RABBITX Security Audit Report</title>
<style>
:root{color-scheme:light;--ink:#172033;--muted:#65718a;--line:#dce3ed;--panel:#fff;--wash:#f3f6fa;--blue:#2458d3;--red:#aa2937;--orange:#a85b05;--green:#17734a}
*{box-sizing:border-box}body{margin:0;background:var(--wash);color:var(--ink);font:15px/1.55 "Segoe UI",Arial,sans-serif}header{background:#101a2d;color:#fff;padding:30px max(24px,calc((100vw - 1180px)/2))}header .brand{font-size:12px;font-weight:700;letter-spacing:.18em;color:#a8c1ff}h1{font-size:28px;line-height:1.2;margin:8px 0}header p{margin:4px 0;color:#c2cee1}main{max-width:1180px;margin:28px auto;padding:0 24px 48px}section{margin:24px 0}.section-head{display:flex;align-items:baseline;justify-content:space-between;gap:16px;margin-bottom:12px}h2{font-size:19px;margin:0}.muted{color:var(--muted);font-size:13px}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.metric,.panel,.finding{background:var(--panel);border:1px solid var(--line);border-radius:10px;box-shadow:0 2px 8px #1b2d4a0a}.metric{padding:16px}.metric .label{display:block;color:var(--muted);font-size:12px}.metric strong{display:block;font-size:26px;margin-top:4px}.panel{padding:18px;overflow:hidden}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:740px}th,td{text-align:left;vertical-align:top;padding:10px 12px;border-bottom:1px solid var(--line)}th{font-size:12px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);background:#f9fbfd}td{font-size:13px;overflow-wrap:anywhere}tr:last-child td{border-bottom:0}.url{font-family:Consolas,"Courier New",monospace;overflow-wrap:anywhere}.badge{display:inline-block;border-radius:20px;padding:2px 9px;background:#e9eef8;color:#31456b;font-size:11px;font-weight:700;text-transform:uppercase}.badge.high,.badge.critical{background:#fdebed;color:var(--red)}.badge.medium{background:#fff1dd;color:var(--orange)}.badge.low,.badge.info{background:#e5f5ed;color:var(--green)}.finding{padding:18px;margin:12px 0}.finding h3{font-size:16px;margin:0 0 8px}.finding p{margin:8px 0}.meta{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:8px}.subtle{font-size:12px;color:var(--muted)}details{margin-top:12px;border-top:1px solid var(--line);padding-top:10px}summary{cursor:pointer;font-weight:600}.evidence{margin-top:10px;padding:12px;background:#f7f9fc;border:1px solid var(--line);border-radius:7px}.evidence dl{display:grid;grid-template-columns:minmax(120px,170px) 1fr;gap:5px 12px;margin:0;font-size:12px}.evidence dt{color:var(--muted);font-weight:600}.evidence dd{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}.empty{padding:18px;color:var(--muted);background:var(--panel);border:1px dashed var(--line);border-radius:8px}footer{max-width:1180px;margin:0 auto;padding:0 24px 24px;color:var(--muted);font-size:12px}@media(max-width:640px){header{padding:24px}main{padding:0 14px 32px;margin-top:16px}.evidence dl{grid-template-columns:1fr}.evidence dd{margin-bottom:8px}}
</style>
</head>
<body>
<header><div class="brand">RABBITX | SECURITY INTELLIGENCE</div><h1>Security Audit Report</h1><p id="project-meta"></p><p id="audit-meta"></p></header>
<main id="report" aria-live="polite"></main>
<footer>Generated by RABBITX | Security Audit Export</footer>
<script id="audit-data" type="application/json">)RABBITX_HTML";
    }

    const char* HtmlScript()
    {
        return R"RABBITX_HTML(</script>
<script>
(function(){
  "use strict";
  var data;
  var root=document.getElementById("report");
  try { data=JSON.parse(document.getElementById("audit-data").textContent); }
  catch(e){ root.textContent="The saved audit data could not be read."; return; }
  function text(value){ if(value===null||value===undefined||value==="") return "-"; return String(value); }
  function el(tag,className,value){ var n=document.createElement(tag); if(className)n.className=className; if(value!==undefined)n.textContent=text(value); return n; }
  function section(title,description){ var s=el("section"); var head=el("div","section-head"); head.appendChild(el("h2","",title)); if(description)head.appendChild(el("span","muted",description)); s.appendChild(head); root.appendChild(s); return s; }
  function badge(value){ var v=text(value).toLowerCase(); return el("span","badge "+v,value); }
  function metric(parent,label,value){ var card=el("div","metric"); card.appendChild(el("span","label",label)); card.appendChild(el("strong","",value)); parent.appendChild(card); }
  function empty(parent,message){ parent.appendChild(el("div","empty",message)); }
  function table(parent,headers){ var wrap=el("div","panel table-wrap"),t=el("table"),thead=el("thead"),tr=el("tr"); headers.forEach(function(h){tr.appendChild(el("th","",h));}); thead.appendChild(tr); t.appendChild(thead); var body=el("tbody"); t.appendChild(body); wrap.appendChild(t); parent.appendChild(wrap); return body; }
  function cell(row,value,className){var c=el("td",className||"",value);row.appendChild(c);return c;}
  function evidence(parent,item){ if(!item)return; var box=el("div","evidence"),dl=el("dl"); ["method","requestedUrl","finalUrl","statusCode","requestHeaders","responseHeaders","bodyExcerpt","observation"].forEach(function(key){ if(item[key]!==undefined&&item[key]!==""){dl.appendChild(el("dt","",key));dl.appendChild(el("dd","",item[key]));} }); box.appendChild(dl);parent.appendChild(box); }
  var auditMeta=document.getElementById("audit-meta");
  auditMeta.textContent=auditMeta.textContent+" | Target: "+text(data.targetUrl)+" | "+text(data.endpointCount)+" endpoints, "+text(data.findingCount)+" findings";
  var scopeSection=section("Scope policy","Requests outside these host, domain, and path rules are blocked"),scope=data.scopePolicy||{},scopePanel=el("div","panel"),scopeColumns=el("div","metrics");
  [["Allowed hosts",scope.allowedHosts,"None; domain rules apply"],["Allowed domains",scope.allowedDomains,"None"],["Allowed paths",scope.allowedPaths,"All paths"]].forEach(function(group){var column=el("div","metric");column.appendChild(el("span","label",group[0]));var list=Array.isArray(group[1])?group[1]:[];if(!list.length)column.appendChild(el("div","subtle",group[2]));else{var ul=el("ul");list.forEach(function(value){ul.appendChild(el("li","",value));});column.appendChild(ul);}scopeColumns.appendChild(column);});
  scopePanel.appendChild(scopeColumns);scopeSection.appendChild(scopePanel);
  var requestBudget=data.requestBudget||{},budgetSection=section("Request budget","Per-run limit and request decisions"),budgetCards=el("div","metrics");budgetSection.appendChild(budgetCards);
  metric(budgetCards,"Limit",requestBudget.maxRequestsPerRun);metric(budgetCards,"Min interval (ms)",requestBudget.minRequestIntervalMs);metric(budgetCards,"Attempted",requestBudget.attemptedRequests);metric(budgetCards,"Successful",requestBudget.successfulRequests);metric(budgetCards,"Failed",requestBudget.failedRequests);metric(budgetCards,"Scope rejected",requestBudget.scopeRejectedRequests);metric(budgetCards,"Budget rejected",requestBudget.budgetRejectedRequests);metric(budgetCards,"Remaining",requestBudget.remainingRequests);
  var config=data.effectiveConfiguration||{},configSection=section("Effective configuration","The settings used for this audit"),configCards=el("div","metrics");configSection.appendChild(configCards);
  metric(configCards,"Timeout (ms)",config.timeoutMs);metric(configCards,"Redirects",config.followRedirects?"Follow":"Stop at first redirect");metric(configCards,"Output format",config.outputFormat);metric(configCards,"Output path",config.outputPath);metric(configCards,"Project persistence",config.persistProject?"Enabled":"Disabled");metric(configCards,"Evidence included",config.reportOptions&&config.reportOptions.includeEvidence?"Yes":"No");metric(configCards,"Probe history included",config.reportOptions&&config.reportOptions.includeProbeHistory?"Yes":"No");
  var overview=section("Overview","Risk distribution and audit totals"),cards=el("div","metrics"); overview.appendChild(cards);
  metric(cards,"Endpoints",data.endpointCount); metric(cards,"Findings",data.findingCount); metric(cards,"Probes",data.probeCount);
  var risk=data.riskSummary||{}; metric(cards,"High risk",Number(risk.high||0)+Number(risk.critical||0)); metric(cards,"Average endpoint risk",risk.averageScore===undefined?"-":risk.averageScore+" / 100");
  var distribution=section("Risk distribution"),dist=el("div","metrics");distribution.appendChild(dist);metric(dist,"Low",risk.low||0);metric(dist,"Medium",risk.medium||0);metric(dist,"High",risk.high||0);metric(dist,"Critical",risk.critical||0);

  var endpointSection=section("Endpoint inventory","Prioritize review using classification, risk, and parameter signals"), endpoints=Array.isArray(data.endpoints)?data.endpoints:[];
  if(!endpoints.length){empty(endpointSection,"No endpoints were recorded.");}else{
    var rows=table(endpointSection,["Method","Endpoint","Class","Risk","Parameters / signals"]);
    endpoints.forEach(function(ep){var row=el("tr");cell(row,ep.method);cell(row,ep.url,"url");cell(row,ep.classification);var riskCell=el("td");riskCell.appendChild(badge(ep.riskScore&&ep.riskScore.level));riskCell.appendChild(el("div","subtle","Score: "+text(ep.riskScore&&ep.riskScore.score)));row.appendChild(riskCell);var signals=[];(Array.isArray(ep.parameters)?ep.parameters:[]).forEach(function(p){var item=text(p.name)+" ("+text(p.type)+")";if(Array.isArray(p.risks)&&p.risks.length)item+=" - "+p.risks.map(function(r){return text(r.type)+": "+text(r.level);}).join(", ");signals.push(item);});(Array.isArray(ep.riskHints)?ep.riskHints:[]).forEach(function(h){signals.push(text(h));});cell(row,signals.join("; "));rows.appendChild(row);});
  }

  var findingSection=section("Findings","Each item includes the recorded evidence snapshot"),findings=Array.isArray(data.findings)?data.findings:[];
  if(!findings.length){empty(findingSection,"No findings were recorded in this audit.");}else findings.forEach(function(f){var card=el("article","finding"),meta=el("div","meta");meta.appendChild(badge(f.severity));meta.appendChild(el("span","badge",f.confidence));meta.appendChild(el("span","subtle",f.ruleId));card.appendChild(meta);card.appendChild(el("h3","",f.title));card.appendChild(el("p","",f.description));if(f.evidence)card.appendChild(el("p","subtle",f.evidence));var details=el("details"),summary=el("summary","","Evidence ("+text(f.evidenceCount||1)+")");details.appendChild(summary);evidence(details,f.requestEvidence);(Array.isArray(f.relatedEvidence)?f.relatedEvidence:[]).forEach(function(item){evidence(details,item);});card.appendChild(details);findingSection.appendChild(card);});

  var probeSection=section("Probe history","Requests recorded during this audit"),probes=Array.isArray(data.probes)?data.probes:[];
  if(!probes.length){empty(probeSection,"No probes were recorded.");}else{var probeRows=table(probeSection,["Probe","Executed","Status","Requested URL","Error"]);probes.forEach(function(p){var row=el("tr");cell(row,p.name);cell(row,p.executed?"Yes":"No");cell(row,p.statusCode);cell(row,p.requestedUrl,"url");cell(row,p.error);probeRows.appendChild(row);});}
})();
</script>
</body>
</html>
)RABBITX_HTML";
    }
}

namespace HTMLReporter
{
    std::string Serialize(
        const std::string& projectName,
        size_t runNumber,
        const std::string& savedAtUtc,
        const std::string& reportJson)
    {
        std::ostringstream out;
        out << HtmlTemplate()
            << EscapeJsonForHtmlScript(reportJson)
            << HtmlScript();

        // Metadata is rendered as escaped HTML text and never interpolated into JavaScript.
        const std::string metadata =
            "Project: " + EscapeHtml(projectName) +
            " | Audit run " + std::to_string(runNumber);

        std::string html = out.str();
        const std::string marker = "<p id=\"project-meta\"></p>";
        const size_t position = html.find(marker);

        if (position != std::string::npos)
        {
            html.replace(
                position,
                marker.size(),
                "<p id=\"project-meta\">" + metadata + "</p>");
        }

        const std::string auditMarker = "<p id=\"audit-meta\"></p>";
        const size_t auditPosition = html.find(auditMarker);

        if (auditPosition != std::string::npos)
        {
            html.replace(
                auditPosition,
                auditMarker.size(),
                "<p id=\"audit-meta\">Audit time: " +
                    EscapeHtml(savedAtUtc) +
                    "</p>");
        }

        return html;
    }

    bool WriteToFile(
        const std::string& projectName,
        size_t runNumber,
        const std::string& savedAtUtc,
        const std::string& reportJson,
        const std::string& path,
        std::string& error)
    {
        error.clear();

        std::ofstream file(
            std::filesystem::u8path(path),
            std::ios::binary | std::ios::trunc);

        if (!file.is_open())
        {
            error = "Unable to open HTML report file: " + path;
            return false;
        }

        const std::string html = Serialize(
            projectName,
            runNumber,
            savedAtUtc,
            reportJson);

        file.write(
            html.data(),
            static_cast<std::streamsize>(html.size()));
        file.close();

        if (!file.good())
        {
            error = "Failed to write HTML report file: " + path;
            return false;
        }

        return true;
    }
}
